<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.6 .\src\lib\assets\stairs.glb
-->

<script>
  import { T, useThrelte } from '@threlte/core';
  import { Float, Grid, MeshRefractionMaterial, useGltf } from '@threlte/extras';
  import { DoubleSide } from 'three';

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const modelUrl = new URL('$lib/assets/stairs.glb', import.meta.url); // URL 생성
  const gltf = useGltf(modelUrl.pathname);

  const { scene } = useThrelte();
  const envMap = scene.environment;
</script>

<Float
  floatIntensity={5}
  rotationIntensity={8}
>
<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.nodes.Cube001.material}
    >
      <T.MeshPhysicalMaterial
        side={DoubleSide}
        roughness={0.25}
        transmission={1}
        thickness={2.5}
        envMap={envMap}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
</Float>
